### PR TITLE
scrypt: move to nan ^2.14.0; fix node 12+ support

### LINKED ISSUE #193: Node v12 support
It seems that the NaN support has changed:

when i compile with node v12.3.0, i have the following errors:
```
error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
```
It seems that v8 functions have been removed.

i found: 
```
Don't use v8 directly, use NAN or napi.
v8::Local<v8::String> val = parameter->ToString(); => Nan::To<v8::String>(parameter) should work.
```

### PR DESCRIPTION
**Pull request by mkrufky**
Node.js 12 bundles a version of v8 with lots of breaking changes, with more coming.
As such, things were moved around in NAN.

This updates node-scrypt to the latest NAN and fixes the build breakage under Node 12.

Also, fix all remaining build warnings to future-proof upcoming v8 changes.

closes #193

### CODE REVIEW

**Comment by Divide-By-0** [comment]
@barrysteyn can we merge this, scrypt is a direct dependency for a number of packages and this would stop breaking

**Comment by barrysteyn** [comment]
Hi, I’ll merge it tomorrow

**Comment by silence48** [comment]
would be nice to merge this!

**Comment by Divide-By-0** [comment]
Bump @barrysteyn !

**Comment by faustbrian** [comment]
@barrysteyn any chance to get this merged soon?

**Comment by barrysteyn** [comment]
Hi all, sorry for taking so long. I was not aware that people are still using this project. Would you like me to publish a version with this merge?

**Comment by faustbrian** [comment]
An npm release would be appreciated @barrysteyn

**Comment by barrysteyn** [comment]
Okay, will do it today then. A major version bump?

**Comment by faustbrian** [comment]
Probably the best to avoid issues for people on the current release.

**Comment by mkrufky** [comment]
I don't think it should be a major version bump, since the PR does not change the public API of node-script.  I would just do a minor version bump.  It does no harm for users of older versions to take this upgrade.

**Comment by barrysteyn** [comment]
okay, will update at the end of my day (I am on PST timezeone).

**Comment by silence48** [comment]
Thanks!

**Comment by barrysteyn** [comment]
Sorry guys, I was having a bit of trouble updating things. I do intend to publish soon though.

Quick question for anyone out there: I was under the impression that Node provides Scrypt encryption in it's own core libraries. If so, why are people still using this?

**Comment by mkrufky** [comment]
There are various existing node.js modules that depend on node-script that have not been rewritten to use other solutions.  node-script still works fine when used with node.js older than 12, but cannot build with later versions of node.js.  Applying this fix is a fine solution, and there is no reason to rewrite all of those other modules if this patch fixes node-script.

**Comment by Divide-By-0** [comment]
Yes, for instance drizzle uses this, and this version of scrypt the only breaking dependency for many projects on npm.

**Comment by barrysteyn** [comment]
Okay, cool. I wasn't really aware of it's popularity :)

**Comment by j4sonzhao** [comment]
Hi, yes. I am trying to install drizzle and unfortunately it is not working because of the node-scrypt dependency :( 

Can you please fix this?

**Comment by mkrufky** [comment]
On second thought, a major version bump is indeed a better idea - I didn't realize that the last release was ~4 years ago.  nodejs/nan itself has dropped support for some older versions of node.js since then, so better to to do a major version bump.

**Comment by barrysteyn** [comment]
Okay... I am struggling with gettting my npm key from old pc (which is not
working). I am about to take out the harddrive to get at it. Sorry this is
taking so long everyone.

**Comment by robinpaulson** [comment]
It's great to see this fix merged. Would it be possible to push the new version to npm? Cheers!

**Comment by robinpaulson** [comment]
for now, this fixed the not-building bug, but it'd be good to see the updates in the npm repo:

$ npm install https://github.com/barrysteyn/node-scrypt/

cheers for all the good work, @barrysteyn

**Comment by HyperCharlie** [comment]
Any chance of getting a new version of this out? There are several blockchain-related projects that still have this as a dependency and it would be really nice to not have to use the head as the version. Thanks!
