### ISSUE TITLE
Does not work with node 0.10

### ISSUE THREAD

**Issue by fiws** [barrysteyn/node-scrypt#4]
At least i can't get it working

sudo apt-get install libssl-dev
git clone https://github.com/barrysteyn/node-scrypt.git ./
node-gyp configure build

```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.9.1
gyp info using node@0.10.0 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/Documents/test/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/user/.node-gyp/0.10.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/user/.node-gyp/0.10.0',
gyp info spawn args   '-Dmodule_root_dir=/home/user/Documents/test/scrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
../src/node-boilerplate/scrypt_node_async.cc: In function ‘v8::Handle<v8::Value> HashAsyncBefore(const v8::Arguments&)’:
../src/node-boilerplate/scrypt_node_async.cc:354:80: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/user/.node-gyp/0.10.0/src/node.h:61:0,
                 from ../src/node-boilerplate/scrypt_node_async.cc:28:
/home/user/.node-gyp/0.10.0/deps/uv/include/uv.h:1397:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/node-boilerplate/scrypt_node_async.cc: In function ‘v8::Handle<v8::Value> VerifyAsyncBefore(const v8::Arguments&)’:
../src/node-boilerplate/scrypt_node_async.cc:457:84: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/user/.node-gyp/0.10.0/src/node.h:61:0,
                 from ../src/node-boilerplate/scrypt_node_async.cc:28:
/home/user/.node-gyp/0.10.0/deps/uv/include/uv.h:1397:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/node-boilerplate/scrypt_node_async.cc: In function ‘v8::Handle<v8::Value> EncryptAsyncBefore(const v8::Arguments&)’:
../src/node-boilerplate/scrypt_node_async.cc:562:86: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/user/.node-gyp/0.10.0/src/node.h:61:0,
                 from ../src/node-boilerplate/scrypt_node_async.cc:28:
/home/user/.node-gyp/0.10.0/deps/uv/include/uv.h:1397:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/node-boilerplate/scrypt_node_async.cc: In function ‘v8::Handle<v8::Value> DecryptAsyncBefore(const v8::Arguments&)’:
../src/node-boilerplate/scrypt_node_async.cc:677:86: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/user/.node-gyp/0.10.0/src/node.h:61:0,
                 from ../src/node-boilerplate/scrypt_node_async.cc:28:
/home/user/.node-gyp/0.10.0/deps/uv/include/uv.h:1397:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
make: *** [Release/obj.target/scrypt_node_boilerplate/src/node-boilerplate/scrypt_node_async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Linux 3.5.0-25-generic
gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/user/Documents/test/scrypt
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v0.9.1
gyp ERR! not ok 
```
