### ISSUE TITLE
Fails to build on Linode Ubuntu 12.04 LTS Profile (32 bit, 3.14.1-x86-linode58)

### ISSUE THREAD

**Issue by mariusk** [barrysteyn/node-scrypt#47]
When compiling, the following output is generated:

```
npm install -g scrypt
npm http GET https://registry.npmjs.org/scrypt
npm http 304 https://registry.npmjs.org/scrypt

> scrypt@3.0.1 install /usr/local/lib/node_modules/scrypt
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/scrypt/build'
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
In file included from ../scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.c:34:0:
/usr/lib/gcc/i686-linux-gnu/4.6/include/emmintrin.h:32:3: error: #error "SSE2 instruction set not enabled"
../scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.c:47:23: error: unknown type name ‘__m128i’
../scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.c:48:29: error: unknown type name ‘__m128i’
../scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.c:48:40: error: unknown type name ‘__m128i’
../scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.c:48:51: error: unknown type name ‘__m128i’
```

Looks like something related to limited SSE support on the node. Some googling around mentions the possibility of missing AVX support as well. Any easy way to attempt to compile without SSE support or similar, or any other ideas to get it building correctly?
