### ISSUE TITLE
Node v12 support

### ISSUE THREAD

**Issue by ellis2323** [barrysteyn/node-scrypt#193]
It seems that the NaN support has changed:

when i compile with node v12.3.0, i have the following errors:
```
error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
```
It seems that v8 functions have been removed.

i found: 
```
Don't use v8 directly, use NAN or napi.
v8::Local<v8::String> val = parameter->ToString(); => Nan::To<v8::String>(parameter) should work.
```

**Comment by chrisveness** [comment]
This repo is no longer maintained.

If you are using `scrypt.hash`, it is now available natively in the Node.js [crypto](https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback) module.

If you are using `scrypt.kdf` / `scrypt.verifyKdf`, [scrypt-kdf](https://github.com/chrisveness/scrypt-kdf) is a close-to-direct replacement.

**Comment by ellis2323** [comment]
I don't use this package but scrypt.js does. I will contact them.
